# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'projectTemplate' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'GoogleSignIn', '~> 4.4.0'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
end
